const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),crypto=require('node:crypto');
const root=require('node:path').resolve(__dirname,'..')+'/',E=require(root+'engine.js'),sandbox={window:{}};vm.runInNewContext(fs.readFileSync(root+'bank.js','utf8'),sandbox);const bank=sandbox.window.LAB_BANK;let count=0;
function eq(a,b){assert.deepEqual(a,b);count++;}function near(a,b,t=1e-10){assert.ok(Math.abs(a-b)<=t*Math.max(1,Math.abs(b)),`${a} ≠ ${b}`);count++;}
eq(bank.length,61);eq(new Set(bank.map(q=>q.id)).size,61);
for(const q of bank){eq(crypto.createHash('sha256').update(fs.readFileSync(root+q.image)).digest('hex'),q.imageSha256);assert.ok(q.solution.length>40&&q.sources.length&&q.options.length>=4);count++;for(const k of q.key){eq(E.grade(q,k,'gate2').status,'correct');near(E.grade(q,k,'gate2').score,2);}const wrong=['A','B','C','D','E'].find(x=>!q.key.includes(x));near(E.grade(q,wrong,'gate2').score,-2/3);near(E.grade(q,q.key[0],'gate1').score,1);eq(E.grade(q,'').status,'skipped');
if(q.nat){const z={...q,type:'NAT',range:q.nat.range};for(const n of [q.nat.value,...q.nat.range])eq(E.grade(z,String(n)).status,'correct');eq(E.grade(z,String(q.nat.range[0]-1)).status,'wrong');near(E.grade(z,String(q.nat.range[1]+1)).score,0);for(const n of ['NaN','Infinity','1+2','0x10','1,000'])eq(E.grade(z,n).status,'invalid');eq(E.grade(z,'').status,'skipped');}
if(q.msq){const z={...q,type:'MSQ',key:q.msq.key};eq(E.grade(z,[...z.key].reverse()).status,'correct');eq(E.grade(z,[]).status,'skipped');const omitted=z.key.length>1?z.key.slice(1):['A'];eq(E.grade(z,omitted).status,'wrong');near(E.grade(z,omitted).score,0);const extra=['A','B','C','D'].find(x=>!z.key.includes(x));if(extra)eq(E.grade(z,[...z.key,extra]).status,'wrong');}}
for(const [s,v] of [['2+3*4',14],['(2+3)*4',20],['2^3^2',512],['-2^2',-4],['2^-2',.25],['sin(30)',.5],['cos(60)',.5],['tan(45)',1],['asin(0.5)',30],['acos(0.5)',60],['atan(1)',45],['ln(e)',1],['log(100)',2],['sqrt(144)',12],['abs(-9)',9],['exp(0)',1],['pow(2,3)',8],['5!',120],['0!',1],['5.67e-8*300^4',459.27],['1e3+2e-2',1000.02],['Ans+M',12],['sinh(0)',0],['cosh(0)',1],['tanh(0)',0]])near(E.evaluate(s,{ans:5,memory:7}),v);
near(E.evaluate('sin(pi/2)',{angle:'RAD'}),1);near(E.convert('32','temperature','°F','°C'),0);near(E.convert('0','temperature','°C','K'),273.15);near(E.convert('1','power','kW','W'),1000);near(E.convert('1','energy','kWh','J'),3600000);near(E.convert('1','length','in','mm'),25.4);near(E.convert('1','pressure','bar','Pa'),100000);
for(const s of ['1/0','sqrt(-1)','tan(90)','(-1)!','171!','process.exit()','alert(1)','2pi','sin()','pow(1)','1;2','<script>','1e999','(',''.padStart(501,'1')]){assert.throws(()=>E.evaluate(s));count++;}
assert.throws(()=>E.convert('-274','temperature','°C','K'));count++;
const report={date:new Date().toISOString(),checks:count,questionScreenshots:61,numericAdaptations:bank.filter(q=>q.nat).length,statementAdaptations:bank.filter(q=>q.msq).length,status:'passed',coverage:'All original keys, screenshot hashes, wrong/blank marking, numeric tolerance endpoints and invalid input, exact MSQ grading, calculator precedence/domain checks and conversions.'};console.log(report);
